config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private
  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :picture_url, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for (flat) do |f| %>
  <div class="form-group">
    <%= f.label :name  %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address  %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :picture_url  %>
    <%= f.text_field :picture_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description  %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Number_of_guests  %>
    <%= f.text_field :number_of_guests, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price_per_night  %>
    <%= f.text_field :price_per_night, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Flat", class: "btn btn-primary" %>
    <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-md-6 col-md-offset-3">
      <div class="flat-form">
        <h1>Edit new flat</h1>
        <%= render 'form', flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12">
      <h1>All our flats</h1>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col col-xs-12 col-md-4">
        <div class="card">

          <div class="flat-card-image" style="background-image: url(<%=flat.picture_url%>)">
          </div>

          <div class="card-content">
            <h3><%= flat.name %></h3>
            <p><%= flat.description %></p>
            <div class="card-details">
              <p><i class="fas fa-users"></i> <%= flat.number_of_guests %></p>
              <p><i class="fas fa-euro-sign"> </i><%= flat.price_per_night %></p>
            </div>
          </div>

          <div class="card-actions">
            <%= link_to "More info", flat_path(flat) %>
            <%= link_to "Edit", edit_flat_path(flat), class: "text-warning" %>
            <%= link_to "Remove", flat_path(flat), class: "text-danger", method: :delete,data:{confirm:"Are you sure?"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 col-md-6 col-md-offset-3">
      <div class="flat-form">
        <h1>Add a new flat</h1>
        <%= render 'form', flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
  <div style="background-image: url('<%= @flat.picture_url %>'); background-size: cover; background-position: center; height: 300px">
  </div>
<div class="container">
  <div class="row">
    <div class="col col-md-8">

      <div class="flat-info">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>

      <div class="description">
          <h1>A bit more about this flat</h1>
          <p><%= @flat.description %></p>

          <div class="" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @flat.address.gsub(' ','+') %>&zoom=13&size=600x300'); height: 300px"></div>
      </div>

      <div class="flat-show-details">
        <h1>Details</h1>
        <div class="details">
          <p><i class="fas fa-users"></i> <%= @flat.number_of_guests %></p>
          <p><i class="fas fa-euro-sign"> </i><%= @flat.price_per_night %></p>
        </div>
      </div>
    </div>

    <div class="col col-md-4 flat-booking"">
      <form>
      <h4>Book this place</h3>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">From:</span>
          <input type="text" class="form-control">
        </div>

        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">To:</span>
          <input type="text" class="form-control">
        </div>

        <input type="submit" value="Book" class="btn btn-success">

      </form>
      <div class="share">
        <p>Share</p>
        <div class="icons">
          <p><i class="fab fa-facebook-square"></i></p>
          <p><i class="fab fa-twitter-square"></i></p>
          <p><i class="fab fa-pinterest-square"></i></p>
          <p><i class="fas fa-envelope-square"></i></p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>